### ISSUE TITLE
Webpacker 6.0.0.beta.2 - SVG files not included in manifest as static file

### ISSUE THREAD

**Issue by fabianzwodrei** [rails/webpacker#2891]
```js

// packs/application.js
// svg file in packs/media/images/icon.svg
require.context('../media', true)

```

It should be used in a .erb file:
```
<%= asset_pack_path 'media/images/icon.svg' %>
```

PNG files from `packs/media` are included in manifest, but all SVG files are missing.

Result:
```
Webpacker::Manifest::MissingEntryError:
Webpacker can't find static/icon.svg
```

The webpacker config folder and `webpacker.yml` are untouched - its a **vanilla webpacker** version in a fresh rails 6 project. 

What is the webpacker-6 way to include SVG from the packs folder?

**Comment by pedrofurtado** [comment]
Hey, @fabianzwodrei ! 👋 

In order to help you, can you please see if this test below works in your application code?

1. Put your svg file in `app/javascript/images/file.svg`
2. In `app/javascript/packs/application.js`, add a line importing this svg image, to make it exportable:

```javascript
import '../images/file.svg'
```

3. Then, in a erb file, add this line:
```erb
<%= asset_pack_path 'media/images/file.svg' %>
```

4. Then, compile with `rails webpacker:compile`. After this, the svg file path appears correctly inside webpage that this erb file is?

Let me know your results 🤝

**Comment by fabianzwodrei** [comment]
Hi @pedrofurtado,

I updated to 6 beta 3 and included the svg file as you described.

`rails weboacker:compile` resulted in the following error, repeated multiple times

```
ERROR in Conflict: Multiple assets emit different content to the same filename js/.br
ERROR in Conflict: Multiple assets emit different content to the same filename .br
```

The Svg file was not included in the manifest.json

**Comment by pedrofurtado** [comment]
Thanks for feedback! 👍 

Hmm 🤔  could you please publish here your package.json and Gemfile? Because it is strange, this error `ERROR in Conflict: Multiple assets emit different content to the same filename .br` was resolved here: https://github.com/rails/webpacker/issues/2828

Maybe the webpacker configuration files in your application is not in sync with new defaults of gem. 

Try execute `rails webpacker:install`, please, as described by https://github.com/rails/webpacker/issues/2828#issuecomment-757474782

let me know your results 👍

**Comment by fabianzwodrei** [comment]
I executed `rails webpacker:install` - that successfully resolved `ERROR in Conflict: Multiple assets emit different content to the same filename .br` 

The webpacker configuration changed. Among other things it changed `source_path` and `source_entry_path`.

The svg is still missing from the `manifest.json`.

Gemfile:

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

gem 'rails', '~> 6.1.1'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'webpacker', '6.0.0.beta.3'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'image_processing', '~> 1.2'

gem 'bootsnap', '>= 1.4.4', require: false

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

```


package.json:

```json

{
  "name": "projectname",
  "private": true,
  "dependencies": {
    "@rails/actioncable": "^6.0.0",
    "@rails/actiontext": "^6.1.1",
    "@rails/activestorage": "^6.0.0",
    "@rails/ujs": "^6.0.0",
    "@rails/webpacker": "^6.0.0-beta.2",
    "autoprefixer": "^10.2.1",
    "css-loader": "^5.0.1",
    "css-minimizer-webpack-plugin": "^1.2.0",
    "mini-css-extract-plugin": "^1.3.4",
    "postcss": "^8.2.4",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-import": "^14.0.0",
    "postcss-loader": "^4.1.0",
    "postcss-preset-env": "^6.7.0",
    "sass": "^1.32.4",
    "sass-loader": "^10.1.1",
    "tailwindcss": "^2.0.2",
    "trix": "^1.2.0",
    "turbolinks": "^5.2.0",
    "webpack": "^5.11.0",
    "webpack-cli": "^4.2.0"
  },
  "version": "0.1.0",
  "devDependencies": {
    "@webpack-cli/serve": "^1.2.2",
    "webpack-bundle-analyzer": "^4.3.0",
    "webpack-dev-server": "^3.11.2"
  },
  "babel": {
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js"
    ]
  },
  "browserslist": [
    "defaults"
  ],
  "babel": {
    "presets": ["./node_modules/@rails/webpacker/package/babel/preset.js"]
  },
  "browserslist": [
    "defaults"
  ]
}


```

**Comment by fabianzwodrei** [comment]
After updating to 
`gem 'webpacker', '6.0.0.beta.3'` as described in the first comment

and renaming the directories `app/javascript` to `app/packs` and `app/javascript/packs` to `app/packs/entrypoints`(according to new webpacker.yml) the svg is served and included! 

Thanks!

**Comment by pedrofurtado** [comment]
@fabianzwodrei Glad to see this worked for you 🎉 

Just a note: Don't use webpacker 6.x in production yet, right? We are making some more changes, to turn it stable for official release.

For a while, use v5.2.1 (or later 5.x stable versions) 👍
