### ISSUE TITLE
Running `bundle exec rake webpacker:install` gives error: `Webpacker configuration file not found /vagrant_host_beeline/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - `

### ISSUE THREAD

**Issue by Taytay** [rails/webpacker#940]
The first time I tried to run `webpacker:install`, it told me that my version of yarn was out of date, so I updated it. Then, I re-ran `webpacker:install` and got this message. I assume I'm doing something wrong, as the install script appears to be copying the webpacker.yml that it's later complaining about. I'm a Rails newb, so me making a mistake is pretty likely...

```
$ bundle exec rake webpacker:install
rake aborted!
Webpacker configuration file not found /vagrant_host_beeline/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /vagrant_host_beeline/config/webpacker.yml
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/configuration.rb:65:in `rescue in load'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/configuration.rb:62:in `load'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/configuration.rb:9:in `refresh'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/commands.rb:14:in `bootstrap'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker.rb:18:in `bootstrap'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/railtie.rb:37:in `block in <class:Engine>'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/vagrant_host_beeline/config/environment.rb:5:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Errno::ENOENT: No such file or directory @ rb_sysopen - /vagrant_host_beeline/config/webpacker.yml
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/configuration.rb:62:in `read'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/configuration.rb:62:in `read'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/configuration.rb:62:in `load'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/configuration.rb:9:in `refresh'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/commands.rb:14:in `bootstrap'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker.rb:18:in `bootstrap'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/webpacker-3.0.2/lib/webpacker/railtie.rb:37:in `block in <class:Engine>'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `instance_exec'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:30:in `run'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/initializable.rb:54:in `run_initializers'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/application.rb:352:in `initialize!'
/vagrant_host_beeline/config/environment.rb:5:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/application.rb:328:in `require_environment!'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/railties-4.2.4/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => rails:template => environment
(See full trace by running task with --trace)
```

**Comment by Taytay** [comment]
It looks like the install script might only allow me to install specific configurations:
https://github.com/rails/webpacker/blob/333f6e9a976e53ad35911a659aa75ad19360cc5e/lib/tasks/installers.rake

So maybe `rake webpacker:install` is not a valid command?

**Comment by Taytay** [comment]
Well, after reading through the code, it does indeed look like the config.yml file needs to be there in order to run the installation script, but the installation script is in charge of copying the `config.yml` file into the right place, so something is amiss...
 
I got around it by copying the webpacker.yml into `config` before running the installation command, and that allowed me to get past the error.
https://raw.githubusercontent.com/rails/webpacker/master/lib/install/config/webpacker.yml

I still presume I'm doing something wrong, but I couldn't figure out what it was.

**Comment by curvo** [comment]
I suspect you are running an instance of spring in one of your terminal windows.  Spring loads classes and caches them in an aggressive way which can get the current set of available classes to be out of sync with your setup.  When spring is running the bootstrap process is triggered within webpacker and somewhere in there it requires the webpacker.yml to already be present.  I would suggest ensuring all of your instances of spring are killed.  Then you can try again with the `bundle exec rake webpacker:install` command.  Or, you can also directly call rake with `rake webpacker:install`.  It's not required that you use `bundle exec` but using that command ensures that rake will be run in the context of the configured gems.  That's not usually necessary to worry about on your local machine, so I usually don't even bother.  It would seem though that by using `bundle exec` you are tapping into the spring set of cached gems.  

Hope that helps!

**Comment by gauravtiwari** [comment]
Yeah, me too. Thanks @curvo

**Comment by drasch** [comment]
running into this same problem with a rails 4.2 app.

**Comment by stujo** [comment]
Also having this problem, Rails 5 app, added 
```
gem 'webpacker', '~> 3.2'
``` 
to Gemfile and ran 
```
 $ bundle exec rails webpacker:install:react
```

got:

```
Configuration config/webpacker.yml file not found. 
Make sure webpacker:install is run successfully before running dependent tasks
```

Gemfile fragment:
```
ruby '2.3.4'
gem 'rails', '~> 5.0.2'
```

**Comment by stujo** [comment]
Hi @Taytay 

Did you try running the main installer first: [See Here](https://stackoverflow.com/a/48999624/2993768)

```
$ bundle exec rails webpacker:install
```

**Comment by dustinbrownman** [comment]
I had this same issue. Just tried to run `bundle exec rails webpacker:install` for the first time on a Rails project. Had to create a dummy `config/webpacker.yml` file (per @Taytay's workaround) for this to work. I'm not sure why this issue is closed as it's still very much a problem.

**Comment by seanhealy** [comment]
I'm also still seeing this issue on Rails 4.2.

**Comment by hass-laughingman** [comment]
@gauravtiwari can this be reopened since number of people (including me) are still seeing this issue. I have tried both the latest v3 stable and the v4 prerelease. This issue is present in both. 

Can confirm this is not spring related. Will use the workaround for now.

**Comment by gauravtiwari** [comment]
@hass-laughingman Sure. 

Could you please share an example where I can reproduce this issue?

**Comment by gauravtiwari** [comment]
Cleaning up since this is an old issue, please reopen with more details.

**Comment by AAYamoldin** [comment]
> I suspect you are running an instance of spring in one of your terminal windows. Spring loads classes and caches them in an aggressive way which can get the current set of available classes to be out of sync with your setup. When spring is running the bootstrap process is triggered within webpacker and somewhere in there it requires the webpacker.yml to already be present. I would suggest ensuring all of your instances of spring are killed. Then you can try again with the `bundle exec rake webpacker:install` command. Or, you can also directly call rake with `rake webpacker:install`. It's not required that you use `bundle exec` but using that command ensures that rake will be run in the context of the configured gems. That's not usually necessary to worry about on your local machine, so I usually don't even bother. It would seem though that by using `bundle exec` you are tapping into the spring set of cached gems.
> 
> Hope that helps!

it helps for me too

**Comment by wahjay** [comment]
Thank you. @curvo

**Comment by emersonxinay** [comment]
eres un capo @curvo  me solucionaste el problema. 
solo puse lo que indicaste y se soluciono el inicio de mi servidor Rails s
bundle exec rake webpacker:install

**Comment by duleorlovic** [comment]
I fix created that file using command line, so this worked for me on Ruby on Rails 4.2 app
```
curl https://raw.githubusercontent.com/rails/webpacker/master/lib/install/config/webpacker.yml > config/webpacker.yml
bundle exec rake webpacker:install
```

**Comment by jhuarancca** [comment]
> I'm having the same issue with Rails 5.0.x. It was not spring related for me, as I stopped spring and when that didn't work, I tried again from a fresh reboot just in case.
> 
> It must be a relatively new issue, because I tested installing webpacker on this same project just a couple of months ago without any problems.
> 
> The workaround of copying https://raw.githubusercontent.com/rails/webpacker/master/lib/install/config/webpacker.yml to my config folder worked for me.

That's work for me, Thanks you..

**Comment by HendrikPetertje** [comment]
same here. I'm on a brand new rails 5.2 project (tried a rails 6.0 after too which has the same problem).

running @duleorlovic's fix seemed to work.

**Comment by gauravtiwari** [comment]
Fixed now in 4.2.0

**Comment by HendrikPetertje** [comment]
thanks!

**Comment by onedebos** [comment]
In Rails 5.0, I ran **bundle exec rails webpacker:install**, this builds the webpacker.yml file and fixes the error. Just remember to restart your rails server to see the changes.

**Comment by dflynn15** [comment]
This issue popped up for an existing Rails app using `rails` at `4.2.11` and `webpacker` at `4.2`. @gauravtiwari was there a PR that fixed this? 

I ended up using the config in `master` like @duleorlovic had above using `curl` but figured I'd report back that at least for me it was still broken.

**Comment by reedjosh** [comment]
@gauravtiwari Same here. Seems the issue is with existing projects? Not using spring ATM.

**Comment by LeandroCGMS** [comment]
> Corrigi o arquivo criado usando a linha de comando, então isso funcionou para mim no aplicativo Ruby on Rails 4.2
> 
> ```
> curl https://raw.githubusercontent.com/rails/webpacker/master/lib/install/config/webpacker.yml > config/webpacker.yml
> bundle exec rake webpacker:install
> ```

Uau!!!!

**Comment by segundogaldames** [comment]
Another alternative is to copy the content of https://raw.githubusercontent.com/rails/webpacker/master/lib/install/config/webpacker.yml to a file called webpacker.yml in the config folder of the project. If the file does not exist it can be created in the config folder.

**Comment by Confusion** [comment]
Issue still exists when trying to switch an existing Rails 5.2 project to webpacker using `bundle exec rake webpacker:install` or `bundle exec rails webpacker:install`. Both with webpacker 4.3.0 and webpacker 5.2.1. 

This is not about spring or about anything weird/uncommon/special about the projects of people that run into this. This is probably broken for everyone trying to switch a project to webpacker, because the webpacker:install code itself simply relies on `config/webpacker.yml` already existing, before it gets to the part where it would bootstrap `config/webpacker.yml`. Manually copying the template from the repo or gem is the only solution.

The stack trace is still essentially the same as in the original report: the Rake task depends on 'environment', which results in Rails.application.initialize! being called, which results in the webpacker railtie being called, which attempts to read webpacker.yml and aborts when it's not there.

```
$ be spring status
Spring is not running.

$ bundle exec rails webpacker:install
rails aborted!
Webpacker configuration file not found rails_app/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - rails_app/config/webpacker.yml
```

**Comment by usershabanov** [comment]
> I fix created that file using command line, so this worked for me on Ruby on Rails 4.2 app
> 
> ```
> curl https://raw.githubusercontent.com/rails/webpacker/master/lib/install/config/webpacker.yml > config/webpacker.yml
> bundle exec rake webpacker:install
> ```

thank you! helped for me as well
